version: "3"
services:
  eureka:
    image: online-video-eureka
    ports:
      - "10090:10090"
    environment:
      - "--spring.profiles.active=pro"

  business:
    image: online-video-business
    links:
      - eureka:discovery
    ports:
      - "10092:10092"
    environment:
      - "--spring.profiles.active=pro"
  gateway:
    image: online-video-gateway
    ports:
      - "10000:10000"
    links:
      - eureka:discovery
    environment:
      - "--spring.profiles.active=pro"
  file:
    image: online-video-file
    ports:
      - "10093:10093"
    links:
      - eureka:discovery
    volumes:
    - /home/jenkinszhang1998/Jobs/LinkedInProjects/onlineVideo/Saved_Files:/home/jenkinszhang1998/Jobs/LinkedInProjects/onlineVideo/Saved_Files
    environment:
      - "--spring.profiles.active=pro"
  system:
    image: online-video-system
    ports:
      - "10091:10091"
    links:
      - eureka:discovery
    environment:
      - "--spring.profiles.active=pro"