server:
  port: 9093
  servlet:
    context-path: /file

spring:
  application:
    name: file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

eureka:
  client:
#    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9090/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15


