server:
  port: 10093
  servlet:
    context-path: /file

spring:
  application:
    name: file
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

eureka:
  client:
#    fetch-registry: false
    service-url:
      defaultZone: http://discovery:10090/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

file:
  dest: /home/jenkinszhang1998/Jobs/LinkedInProjects/onlineVideo/Saved_Files/
  url: http://34.105.212.23:10000/file/f/

oss:
  endpoint: http://oss-cn-shanghai.aliyuncs.com/
  accessKeyId: LTAI4G8AdWYM9h3QrdGfKL9W
  accessKeySecret: C7hEkQwJSmiFfn7CtcyJWEZ9oAyjPY
  bucket: course-onlinevideo
  url: http://course-onlinevideo.oss-cn-shanghai.aliyuncs.com/
vod:
  accessKeyId: LTAI4G8AdWYM9h3QrdGfKL9W
  accessKeySecret: C7hEkQwJSmiFfn7CtcyJWEZ9oAyjPY

logging:
  config: classpath:logback-pro.xml