server:
  port: 10093
  servlet:
    context-path: /file

spring:
  application:
    name: file
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

eureka:
  client:
#    fetch-registry: false
    service-url:
      defaultZone: http://discovery:10090/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

file:
  dest: /home/jenkinszhang1998/Jobs/LinkedInProjects/onlineVideo/Saved_Files/
  url: http://35.246.12.177:10000/file/f/

logging:
  config: classpath:logback-pro.xml