spring:
  datasource:
    url: jdbc:mysql://35.246.12.177:3306/onlineVideo?serverTimezone=Asia/Shanghai
    username: root
    password: Qianqi971126!
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    jedis:
      pool:
        max-active: 10
        max-idle: 10
    host: 35.246.12.177

mybatis:
  type-aliases-package: com.jenkins.server
  mapper-locations: classpath*:mapper/**/*Mapper.xml


logging:
  level:
    com.jenkins.server.mapper:
      trace