server:
  port: 9000

spring:
  application:
    name: GateWay
  cloud:
    gateway:
      routes:
        - id: system
#          uri: http://localhost:9091
          uri: lb://system
          predicates:
            - Path=/system/**
          filters:
            - name: LoginAdmin
        - id: business
#          uri: http://localhost:9092
          uri: lb://business
          predicates:
            - Path=/business/**
          filters:
            - name: LoginAdmin
        - id: file
#          uri: http://localhost:9093
          uri: lb://file
          predicates:
            - Path=/file/**
          filters:
            - name: LoginAdmin
  redis:
    host: 35.246.12.177

eureka:
  client:
#    fetch-registry: false
    service-url:
      defaultZone: http://discovery:9090/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

