server:
  port: 9091
  servlet:
    context-path: /system

spring:
  application:
    name: system
  redis:
    host: 35.246.12.177

eureka:
  client:
#    fetch-registry: false
    service-url:
      defaultZone: http://discovery:9090/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15


