server:
  port: 10092
  servlet:
    context-path: /business

spring:
  application:
    name: business

eureka:
  client:
#    fetch-registry: false
    service-url:
      defaultZone: http://discovery:10090/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    


logging:
  config: classpath:logback-pro.xml