server:
  port: 10090

spring:
  application:
    name: EurekaServer

eureka:
  client:
#    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
  server:
    eviction-interval-timer-in-ms: 2000
logging:
  config: classpath:logback-pro.xml
